TaskProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("taskapp.urls", namespace="taskapp")),
    path("account/", include("account.urls", namespace="account")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='signup'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),

]

taskapp/urls.py
from django.urls import path
from taskapp import views

app_name = "taskapp"

urlpatterns = [
    path("", views.index, name="home"),
    path("create-task/", views.create_task, name="task-create"),
    path("update-task/<str:pk>/", views.update_task, name="task-update"),
    path("delete-task/<str:pk>/", views.delete_task, name="task-delete")
]

account/models.py
from django.db import models

# Create your models here.

taskapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User

User = get_user_model()

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length = 250)
    description = models.TextField(blank = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    completed = models.BooleanField(default = False)

    def __str__(self):
        return self.title


    @property
    def preview(self):
        return self.description[:50]

    class Meta:
        ordering = ['-updated_at','-created_at']

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password1', 'password2',]

taskapp/forms.py
from django import forms
from taskapp.models import Task

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        # fields = '__all__'
        # exclude = ['user']
        fields = ['title', 'description', 'completed']

account/views.py
from django.shortcuts import render, redirect
from account.forms import RegistrationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

# Create your views here.
def register(request):
    form = RegistrationForm()

    if request.method == 'POST':
        form = RegistrationForm(request.POST or None)
        # username = request.POST['username']
        # password = request.POST['password1']
        if form.is_valid():
            form.save()
            # user = authenticate(request, username=username, password=password)
            # if user is not None:
            #     login(request, user)

            return redirect("account:login")
            # return redirect("taskapp:home")

    
    context = {
        "form":form
    }

    return render(request, "account/register.html", context)

def login_view(request):
    form = AuthenticationForm()

    if request.method == "POST":

        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)

            return redirect("taskapp:home")
        else:
            messages.error(request, "Username or Password is incorrect!")

    context = {
        'form':form
    }

    return render(request, 'account/login.html', context)


def logout_view(request):
    logout(request)

    return redirect('account:login')

taskapp/views.py
from django.shortcuts import render, redirect
from taskapp.models import Task
from taskapp.forms import TaskForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):

    # print(request.GET['search-area'])
    search_query = request.GET.get('search-area')
    print(search_query)
    if search_query is None or search_query == "":
        tasks = Task.objects.filter(user=request.user)
        count = Task.objects.filter(user=request.user, completed=False).count()
    else:
        tasks = Task.objects.filter(user=request.user, title__icontains=search_query)
        count = Task.objects.filter(user=request.user, completed=False, title__icontains=search_query).count()

    context = {
        "tasks":tasks,
        "count":count,
        "search_query":search_query,
    }

    return render(request, "taskapp/index.html", context)


def create_task(request):
    form = TaskForm()
    title = "Create Task"

    if request.method=="POST":
        form = TaskForm(request.POST or None)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            
        return redirect("taskapp:home")

    context = {
        "form":form,
        "title":title,
    }

    return render(request, 'taskapp/task_form.html', context)


def update_task(request, pk):
    task = Task.objects.get(pk=pk)
    form = TaskForm(instance=task)
    title = "Update Task"

    if request.method=="POST":
        form = TaskForm(request.POST or None, instance=task)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            
        return redirect("taskapp:home")

    context = {
        "form":form,
        "title":title,
    }

    return render(request, 'taskapp/task_form.html', context)

def delete_task(request, pk):
    task = Task.objects.get(pk=pk)

    if request.method=="POST":
        task.delete()

        return redirect("taskapp:home")

    context = {
        "task":task
    }

    return render(request, "taskapp/task_confirm_delete.html", context)

taskapp/templates/taskapp/index.html
{% extends 'partials/base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}
<div class="header-bar">
    <div>
        <h1>Hello {% if request.user.get_full_name%}{{request.user.get_full_name|title}}{% else %}{{request.user}}{% endif %}</h1>
        <h3 style="margin:0">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s" }}</h3>
    </div>

    {% if request.user.is_authenticated %}
    <a href="{% url 'account:logout' %}">Logout</a> 
    {% else %}
    <a href="{#% url 'login' %#}">Login</a> 
    {% endif %}
</div>


<div id="search-add-wrapper">
    <form method="GET" style="display: flex;">
        <input type='text' name='search-area' placeholder="Search your task" value="{% if search_query %}{{search_query}}{% endif %}">
        <input class="button" type="submit" value='Search'>
    </form>
    {% if tasks|length > 0 %}
    <a id="add-link" href="{% url 'taskapp:task-create' %}">&#x2b;</a>
    {% endif %}
</div>



<div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper" data-position="{{task.pk}}">
        <div class="task-title">
            {% if task.completed %}
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'taskapp:task-update' task.id %}">{{task}}</a></s></i> 
            {% else %}
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'taskapp:task-update' task.id %}">{{task}}</a> {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'taskapp:task-delete' task.id %}">&#215;</a>
        </div>
    </div>

    {% empty %}
    <div style="text-align: center; padding-bottom: 10px; line-height: 1em;">
        <h3>No new tasks are created.</h3>
        <h3>Create a <a style="text-decoration: none; color: #e53935;" href="{% url 'taskapp:task-create' %}">New task</a> ! </h3>
    </div>
    {% endfor %}
</div>

{% endblock content %}

taskapp/templates/taskapp/task_confirm_delete.html
{% extends 'partials/base.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'taskapp:home' %}">&#8592; Go Back</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Are your sure you want to delete this task? <b>"{{task}}"</b> </p>
        <input class="button" type="submit" value="Delete" />
    </form>
</div>



{% endblock content %}

taskapp/templates/taskapp/task_form.html
{% extends 'partials/base.html' %}
{% block title %}{{title}}{% endblock title %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'taskapp:home' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>


{% endblock content %}

templates/partials/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %} | Task App</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="static/css/style.css"> -->
</head>

<body>

    <div class="container">
        {% block content %} {% endblock content %}
    </div>

</body>


</html>